from typing import Protocol, List
from app.profile.schemas import ProfileOnboardRequest
from app.pet.schemas import PetCreate
from app.service.schemas import OfferedServiceCreate
from uuid import UUID


class InternalOnboardingService(Protocol):
    def onboard_profile(self, *, profile_id: UUID, onboard_req: ProfileOnboardRequest) -> None: ...
    def onboard_pet(self, *, profile_id: UUID, new_pet_req: PetCreate) -> None: ...
    def onboard_offered_services(self, *, profile_id: UUID, offered_services: List[OfferedServiceCreate]) -> None: ...
    def complete_onboard(self, *, profile_id: UUID) -> None: ...
