"""Add autoincrement to review

Revision ID: 2d7f618c81c5
Revises: 96efb825b1c7
Create Date: 2025-10-11 06:31:54.002197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7f618c81c5'
down_revision: Union[str, Sequence[str], None] = '96efb825b1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE review_id_seq")
    op.execute("ALTER TABLE review ALTER COLUMN id SET DEFAULT nextval('review_id_seq')")
    op.execute("ALTER SEQUENCE review_id_seq OWNED BY review.id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
