"""Update profile with necessary details

Revision ID: 8f4194f78c05
Revises: b2e3c26086b8
Create Date: 2025-09-25 02:12:31.475863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4194f78c05'
down_revision: Union[str, Sequence[str], None] = 'b2e3c26086b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('profile', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('contact_num', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('address', sa.String(), nullable=True))
    op.add_column('profile', sa.Column('onboarded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('profile', sa.Column('type', sa.String(), nullable=False))
    op.add_column('profile', sa.Column('profile_picture', sa.String(), nullable=True))
    op.drop_column('profile', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('profile', 'profile_picture')
    op.drop_column('profile', 'type')
    op.drop_column('profile', 'onboarded')
    op.drop_column('profile', 'address')
    op.drop_column('profile', 'contact_num')
    op.drop_column('profile', 'last_name')
    op.drop_column('profile', 'first_name')
    # ### end Alembic commands ###
