"""Remove booking day table and add date to Booking and add unique to booking

Revision ID: 96efb825b1c7
Revises: f7327623c10b
Create Date: 2025-10-11 05:47:11.421897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96efb825b1c7'
down_revision: Union[str, Sequence[str], None] = 'f7327623c10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_booking_day')
    op.add_column('service_booking', sa.Column('date', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uix_pet_date_offered_svc', 'service_booking', ['pet_id', 'date', 'offered_service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_pet_date_offered_svc', 'service_booking', type_='unique')
    op.drop_column('service_booking', 'date')
    op.create_table('service_booking_day',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', postgresql.ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='day'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['service_booking.id'], name=op.f('service_booking_day_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'day', name=op.f('service_booking_day_pkey'))
    )
    # ### end Alembic commands ###
