"""Add status field to booking and billing

Revision ID: f7327623c10b
Revises: 8f4194f78c05
Create Date: 2025-10-11 05:16:03.549706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7327623c10b'
down_revision: Union[str, Sequence[str], None] = '8f4194f78c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    paystatus = sa.Enum('Pending', 'Paid', name='paystatus')
    bookingstatus = sa.Enum(
        'Pending', 'Cancelled', 'Accepted', 'Declined', 'PendingPayment', 'Completed',
        name='status'
    )

    bind = op.get_bind()
    paystatus.create(bind, checkfirst=True)
    bookingstatus.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('status', sa.Enum('Pending', 'Paid', name='paystatus'), nullable=False))
    op.create_unique_constraint('uix_service_caretaker', 'offered_service', ['service_id', 'caretaker_id'])
    op.add_column('service_booking', sa.Column('status', sa.Enum('Pending', 'Cancelled', 'Accepted', 'Declined', 'PendingPayment', 'Completed', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_booking', 'status')
    op.drop_constraint('uix_service_caretaker', 'offered_service', type_='unique')
    op.drop_column('billing', 'status')
    # ### end Alembic commands ###
