from typing import Protocol, List
from .schemas import BookingCreate, Booking as BookingDTO
from uuid import UUID


class ExternalBookingService(Protocol):
    def get_booking(self, *, caller_id: UUID, booking_id: int) -> BookingDTO: ...


class InternalBookingService(ExternalBookingService, Protocol):
    def create_booking(self, *, owner_id: UUID, booking_create: BookingCreate) -> int: ...
    def accept_booking(self, *, caretaker_id: UUID, booking_id: int) -> None: ...
    def decline_booking(self, *, caretaker_id: UUID, booking_id: int) -> None: ...
    def cancel_booking(self, *, caller_id: UUID, booking_id: int) -> None: ...
    def pending_payment_booking(self, *, caretaker_id: UUID, booking_id: int) -> None: ...
    def get_bookings_by_caller_id(self, *, caller_id: UUID) -> List[BookingDTO]: ...
    def pay_booking_bill(self, *, caller_id: UUID, billing_id: int) -> None: ...
    def _complete_booking(self, *, booking_id: int) -> None: ...
